# travis-ci.org definition for oct2py build

# After changing this file, check it on:
#   http://lint.travis-ci.org/

# http://conda.pydata.org/docs/travis.html
language: python

env:
    - CONDA="python=2.6 numpy=1.6 scipy=0.11"
    - CONDA="python=2.7 numpy scipy"
    - CONDA="python=3.3 numpy scipy"
    - CONDA="python=3.4 numpy scipy"

before_install:
  - sudo apt-get update -qq;
  - if [[ $CONDA == "python=2.7*" ]]; then
        sudo apt-get install -qq octave;
    else
        sudo apt-add-repository -y ppa:picaso/octave;
        sudo apt-get update -qq;
        sudo apt-get install -qq octave liboctave-dev;
    fi
  - wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - conda create -n test $CONDA IPython nose pip coverage"
  - source activate test
  - pip install coveralls

install:
  - export PYTHONWARNINGS=all
  - python setup.py install

script:
    # turn off PTY on py3.4 (just for variety)
  - if [[ $CONDA == "python=3.4*" ]]; then
       export NO_PTY = 1
    fi
    # run coverage on py2.7, regular on others
  - if [[ $CONDA == "python=2.7*" ]]; then
      nosetests -v --exe --with-doctest --with-cov --cover-package oct2py oct2py
    else
      nosetests --exe -v -with-doctest oct2py
    fi

after_success:
    - if [[ $CONDA == "python=2.7*" ]]; then
          coveralls
      fi
