# travis-ci.org definition for oct2py build

# After changing this file, check it on:
#   http://lint.travis-ci.org/

# http://conda.pydata.org/docs/travis.html
language: python

install:
  - sudo apt-get update;
    sudo apt-get install octave;
  - wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a

script:
  # run with baseline numpy, scipy and Octave versions
  - conda create -n py27 numpy scipy IPython nose pip
  - source activate py27
  - python setup.py install
  - pushd ..
  - nosetests --exe -v --with-doctest --with-cov --cover-package oct2py --cov-config blink1073/oct2py/.coveragerc oct2py;
  - source deactivate
  - popd
  # upgrade Octave to 3.6
  - sudo apt-add-repository -y ppa:picaso/octave;
    sudo apt-get update;
    sudo apt-get install octave liboctave-dev;
    # run with python 3.3
  - conda create -n py33 python=3.3 numpy scipy IPython nose pip
  - source activate py33
  - python setup.py install
  - pushd ..
  - nosetests --exe -v
  - source deactivate
  # run with python 3.4
  - conda create -n py34 python=3.4 numpy scipy IPython nose pip
  - source activate py34
  - python setup.py install
  - pushd ..
  - nosetests --exe -v
  - source deactivate
  - popd

after_success:
    - coveralls
