# travis-ci.org definition for oct2py build
language: python

python:
    - 2.7
    - 3.2

install:
    - sudo apt-get install python-dev libatlas-base-dev liblapack-dev
    - sudo apt-get install gfortran octave-3.2
    - pip install numpy scipy
    - python setup.py install

script:
    - nosetests oct2py