# travis-ci.org definition for oct2py build

language: python
python:
  - 2.7
  - 3.2
  - 3.3
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy python-scipy octave
install:
  - pip install coveralls --use-mirrors
  - pip install nose --use-mirrors
  - pip install coverage --use-mirrors
  - python setup.py install
script:
  - nosetests -v --with-coverage --cover-package=oct2py
  - iptest -v IPython.extensions.tests.test_octavemagic
after_success:
  coveralls