# travis-ci.org definition for oct2py build

# After changing this file, check it on:
#   http://lint.travis-ci.org/

# http://conda.pydata.org/docs/travis.html
language: python

env:
    - CONDA="python=2.7 numpy>=1.11 scipy=0.17.0"
    - CONDA="python=3.5 scipy"
    - CONDA="python=3.6 scipy"

before_install:
  - sudo apt-add-repository -y ppa:picaso/octave;
  - sudo apt-get update -qq;
  - sudo apt-get install -qq octave liboctave-dev;
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - travis_retry conda create -n test $CONDA jupyter pytest pip
  - source activate test
  - travis_retry pip install codecov

install:
  - export PYTHONWARNINGS=all
  - python setup.py install

script:
    # run coverage on py3.5, regular on others
  - which nosetests
  - which python
  - python -c "import octave_kernel"
  - if [[ $CONDA == python=2.7* ]]; then
      make test
      jupyter nbconvert --to notebook --execute --ExecutePreprocessor.kernel_name=python2 --ExecutePreprocessor.timeout=60 --stdout example/octavemagic_extension.ipynb > /dev/null;
    else
      make cover
      jupyter nbconvert --to notebook --execute --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=60 --stdout example/octavemagic_extension.ipynb > /dev/null;
    fi
  - make docs

after_success:
    - codecov
