# vim ft=yaml
# travis-ci.org definition for oct2py build
#
# We pretend to be erlang because we need can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy, and scipy,
# and it is impractical to build them

language: erlang
env:
    - PYTHON=python PYSUF=''
    - PYTHON=python3 PYSUF=3
install:
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-scipy
    - sudo apt-get install $PYTHON-setuptools
    - sudo apt-get install $PYTHON-nose
    - sudo apt-get install octave3.2
    - $PYTHON setup.py build
    - sudo $PYTHON setup.py install
script:
    # Change into an innocuous directory and find tests from installation
    - mkdir for_test
    - cd for_test
    - nosetests --exe -v --cover-package=oct2py oct2py

